### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by matthojo** [matthojo/project-m#3]
**Description of task**
The search bar is the main focus of the site. A seamless search experience returning the desired results in the fastest time possible.

**Todos**
- [ ] Must return relevant results
- [ ] Must support localisation
- [ ] Must be style-able
- [ ] All the speed
- [ ] a11y results

**Resources**

- https://www.algolia.com/ (https://gdpr.algolia.com/)
- https://azure.microsoft.com/en-us/services/search/
- https://www.elastic.co/
