### ISSUE TITLE
Collect mental health resources 

### ISSUE THREAD

**Issue by matthojo** [matthojo/project-m#5]
**Description of task**
Collect mental health resources from submitted sites.

**Todos**
- [ ] Obtain resources in a non-invasive manner
  * Prevent too many passes of one site
- [ ] Store results into a database
- [ ] Optimise database for result returning
- [ ] Collect results from store of submitted sites
  * Queue collection

**Resources**
- Redis
- https://www.mind.org.uk/sitemap

**Potential Databases**
- Postgres

**Comment by Chandu0009** [comment]
Amazing! I like to share it with all my friends and hope they will like this information. 
Regards
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Training In Hyderabad</a>
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Online Training</a>
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Training</a>
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Training Online </a>
